common = {
#    'groups' : ['EventInfo','PV','TagVar','JetInfo','JetSV','JetTrack','CSVTagVar','PFElectron','PFMuon','JetDeepCSV','PatMuon','PatElec','JetDeepFlavour'],
    'groups' : ['EventInfo','PV','TagVar','JetInfo','JetSV','JetTrack','CSVTagVar','PFElectron','PFMuon','JetDeepCSV','PatMuon','PatElec'],
    'eras' : ['Run3'],
    'miniAOD' : True,
    'usePuppi' : False,
    'usePuppiForFatJets' : True,
    'usePuppiForBTagging' : False,
    'useLegacyTaggers' : True,
    'mcGlobalTag' : 'auto:110X_mcRun3_2021_realistic_v6',
    'remakeAllDiscr' : True,
    'maxJetEta' : 4.5,
    'usePrivateJEC' : False,
    'jecDBFileMC' : '',
    'inputFiles' : ['/store/mc/Run3Winter20DRPremixMiniAOD/TT_TuneCP5_14TeV-powheg-pythia8/MINIAODSIM/110X_mcRun3_2021_realistic_v6-v2/20000/FCDB1A9C-FC38-FA40-B41E-0DA8F93702AD.root'],
    # 'JPCalibration' : 'JPcalib_MC81X_v0',

#Luca     'usePuppi' : True,
#Luca     'usePuppiForFatJets' : False,
#Luca     'usePuppiForBTagging' : True,
#Luca     'mcGlobalTag' : '90X_upgrade2023_realistic_v1',
#Luca     'miniAOD' : False,
#Luca     'remakeAllDiscr' : True,
#Luca     'runIVF' : True, 
#Luca     'maxJetEta' : 4.5,
#Luca     'usePrivateJEC' : True,
#Luca     'jecDBFile' : 'PhaseIISummer16_25nsV3', 
#Luca     'inputFiles' : ['/store/mc/PhaseIIFall16DR82/TT_TuneCUETP8M1_14TeV-powheg-pythia8/AODSIM/PU200_90X_upgrade2023_realistic_v1-v1/110000/FCEB8448-98F6-E611-BA63-1866DAEB5D80.root',],
#Luca     'storeCSVTagVariables' : False,
#Luca     'JPCalibration' : 'JPcalib_MC81X_v0',
}
