common = {
#    'groups' : ['EventInfo','PV','TagVar','JetInfo','JetSV','JetTrack','CSVTagVar','PFElectron','PFMuon','JetDeepCSV','PatMuon','PatElec','JetDeepFlavour'],
    'groups' : ['EventInfo','PV','TagVar','JetInfo','JetSV','JetTrack','CSVTagVar','PFElectron','PFMuon','JetDeepCSV','PatMuon','PatElec'],
    'eras' : ['Run3'],
    'miniAOD' : True,
    'usePuppi' : False,
    'usePuppiForFatJets' : True,
    'usePuppiForBTagging' : False,
    'mcGlobalTag' : 'auto:110X_mcRun3_2021_realistic_v6',
    'remakeAllDiscr' : True,
    'maxJetEta' : 4.5,
    'usePrivateJEC' : False,
    'jecDBFileMC' : '',
    'inputFiles' : ['/store/mc/Run3Winter20DRPremixMiniAOD/TT_TuneCP5_14TeV-powheg-pythia8/MINIAODSIM/110X_mcRun3_2021_realistic_v6-v2/20000/FCDB1A9C-FC38-FA40-B41E-0DA8F93702AD.root'],
    # 'JPCalibration' : 'JPcalib_MC81X_v0',
}
